# Source: https://github.com/mariomka/regex-benchmark
#
# The benchmark metholodgy section for this benchmark is extremely sparse, but
# after looking at some example programs[1], it's clear that it slurps up the
# entire haystack and just finds all matches. That is, this is *not* a line
# oriented benchmark.
#
# The benchmark *also* includes the compile times of regexes. But... it uses
# a haystack that is so small that the compile times can actually have a
# measurable impact on the final results. The benchmark makes an attempt to
# control for this by providing an "optimized" version, which would be better
# called "where we actually compare apples to apples."
#
# Anyway, in this benchmark suite, we separate compile time from search
# time. And here, we only measure search time, so it is not quite a precise
# reproduction of mariomka's benchmark.
#
# Another difference from mariomka's benchmark is that we actually try to
# control for equivalent functionality between regex engines, instead of
# comparing apples with oranges. For example, we don't let one regex engine
# run with Unicode enabled and another run without it enabled.
#
# [1]: https://github.com/mariomka/regex-benchmark/blob/17d073ec864931546e2694783f6231e4696a9ed4/rust/src/main.rs

[[bench]]
model = "count-spans"
name = "email"
regex = '[\w\.+-]+@[\w\.-]+\.[\w\.-]+'
haystack = { path = "imported/mariomka.txt" }
count = 1636
engines = [
  'rust/regex',
  'rust/regex/meta',
  'rust/regexold',
  'regress',
  're2',
  'go/regexp',
  'pcre2/jit',
  'pcre2',
  'python/re',
  'python/regex',
]

[[bench]]
model = "count-spans"
name = "uri"
regex = '[\w]+://[^/\s?#]+[^\s?#]+(?:\?[^\s#]*)?(?:#[^\s]*)?'
haystack = { path = "imported/mariomka.txt" }
count = 215_980
engines = [
  'rust/regex',
  'rust/regex/meta',
  'rust/regexold',
  'regress',
  're2',
  'go/regexp',
  'pcre2/jit',
  'pcre2',
  'python/re',
  'python/regex',
]

[[bench]]
model = "count-spans"
name = "ip"
regex = '(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9])\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9])'
haystack = { path = "imported/mariomka.txt" }
count = 61
engines = [
  'rust/regex',
  'rust/regex/meta',
  'rust/regexold',
  'regress',
  're2',
  'go/regexp',
  'pcre2/jit',
  'pcre2',
  'python/re',
  'python/regex',
]
